name: ps_qtnativeapp
on: [push]

env:
  QT_HOME: /tmp/PS_QT
  QT_INSTALLER_HOME: /tmp/QTIFW
  MAC_S3_BUCKET_STAGING: s3://ps.public.resources/native-app/staging/darwin/
  LINUX_S3_BUCKET_STAGING: s3://ps.public.resources/native-app/staging/linux/
  MAC_S3_BUCKET_DEV: s3://ps.public.resources/native-app/dev/darwin/
  LINUX_S3_BUCKET_DEV: s3://ps.public.resources/native-app/dev/linux/
  RANDOM_VARIABLE: "Hello, this is Alex"

jobs:
  build-osx:
    runs-on: macos-12
    env: 
      ANOTHER_VARIABLE: "$LINUX_S3_BUCKET_DEV"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "run_id ${{ github.run_id }}"
      - run: echo "run_number ${{ github.run_number }}"
      - run: echo "run_attempt ${{ github.run_attempt }}"
      - run: |
          echo "echo $ ANOTHER_VARIABLE"
          echo $ANOTHER_VARIABLE
      - run: |
          echo "echo $ {{ env. ANOTHER_VARIABLE }}"
          echo ${{ env.ANOTHER_VARIABLE }}
      - name: conditional
        if: ${{ env.ANOTHER_VARIABLE == 's3://ps.public.resources/native-app/dev/linux/' }}
        run: export ANOTHER_VARIABLE=$LINUX_S3_BUCKET_STAGING
      - run: echo $ANOTHER_VARIABLE
      - run: echo ${{ env.ANOTHER_VARIABLE }}
        
      
