name: ps_qtnativeapp
on: [push]

env:
  QT_HOME: /tmp/PS_QT
  QT_INSTALLER_HOME: /tmp/QTIFW
  MAC_S3_BUCKET_STAGING: s3://ps.public.resources/native-app/staging/darwin/
  LINUX_S3_BUCKET_STAGING: s3://ps.public.resources/native-app/staging/linux/
  MAC_S3_BUCKET_DEV: s3://ps.public.resources/native-app/dev/darwin/
  LINUX_S3_BUCKET_DEV: s3://ps.public.resources/native-app/dev/linux/
  RANDOM_VARIABLE: "Hello, this is Alex"

jobs:
  job0:
    runs-on: macos-12
    env:
      ANOTHER_VARIABLE: $LINUX_S3_BUCKET_DEV
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
  job1-dev:
    needs: job0
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/release_v*' }}
    steps:
      - run: echo "Job 1 dev"
  
  job2-staging:
    needs: job0
    runs-on: ubuntu-latest
    if:  ${{ github.ref == 'refs/heads/release_v*' }}
    steps:
      - run: echo "Job2 staging"
      
